name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_9zM2LKqO7ET4QnGLydabLOX0
          vercel-project-id: prj_nE8gV2Y24DZ6ZCGcYF3SUHtIAJOP
          vercel-args: '--prod'
